spring:
  datasource:
      url: jdbc:h2:mem:default;DB_CLOSE_DELAY=-1
      username: sa
      password:
  liquibase:
    changeLog: classpath:/liquibase/db.changelog-master.xml
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    enabled: true
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: '*'
